version: '3'
services:

  db:
    image: mysql:5.7
    container_name: prediction-league-db
    volumes:
      - ${PWD}/docker/db/mysql-override.cnf:/etc/mysql/mysql.conf.d/mysql-override.cnf
      - ${PWD}/docker/db/data:/var/lib/mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prediction-league
      MYSQL_USER: pl_user
      MYSQL_PASSWORD: pl_pwd

  assets:
    image: node:13.10
    container_name: prediction-league-assets
    volumes:
      - ${PWD}:/app
    working_dir: /app
    command: bash -c "npm install && npm run watch"

  app:
    image: golang:1.16
    container_name: prediction-league-app
    env_file: ${PWD}/infra/app.docker.env
    depends_on:
      - db
      - assets
    volumes:
      - ${PWD}:/go/src/app
    working_dir: /go/src/app
    ports:
      - 3000:3000
    command: go run service/cmd/api/main.go

  db_test:
    image: mysql:5.7
    container_name: prediction-league-db-test
    volumes:
      - ${PWD}/docker/db/mysql-override.cnf:/etc/mysql/mysql.conf.d/mysql-override.cnf
    ports:
      - 33070:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prediction-league-test
      MYSQL_USER: pl_test_user
      MYSQL_PASSWORD: pl_test_pwd

  app_test:
    image: golang:1.16
    container_name: prediction-league-app-test
    env_file: ${PWD}/infra/test.docker.env
    depends_on:
      - db_test
    volumes:
      - ${PWD}:/go/src/app
    working_dir: /go/src/app
    command: go test -v ./...
