version: '3'
services:

  db:
    image: mysql:5.7
    container_name: pl-service-db
    volumes:
      - ${PWD}/docker/db/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pl_service
      MYSQL_USER: pl_service_user
      MYSQL_PASSWORD: pl_service_user

  app:
    image: golang:1.14
    container_name: pl-service-app
    depends_on:
      - db
    volumes:
      - ${PWD}:/go/src/app
    working_dir: /go/src/app
    ports:
      - 3000:3000
    command: go run service/main.go
